-- ============================================
-- Migration: Create Core Events Tables
-- Created: 2025-01-25
-- Purpose: Create events and event_schedules tables (core event entities)
-- Dependencies: 20250125000000_extensions_and_enums.sql, 20250125000001_create_venues.sql
-- ============================================

-- ============================================
-- EVENTS TABLE (Master Record)
-- ============================================

-- Events table is the central entity for all fashion events
-- Links organizers, venues, and all event-related data
create table events (
  id uuid default gen_random_uuid() primary key,
  organizer_id uuid references auth.users(id) on delete restrict not null,
  venue_id uuid references venues(id) on delete set null,
  
  -- Basic information
  title text not null,
  slug text unique not null, -- SEO-friendly URL slug (e.g., 'summer-fashion-night-2025')
  description text, -- Full description (Markdown allowed)
  short_description text, -- For cards/SEO (150 chars recommended)
  
  -- Status and visibility
  status event_status default 'draft',
  is_public boolean default false,
  
  -- Timing
  start_time timestamptz not null,
  end_time timestamptz,
  timezone text default 'UTC',
  
  -- Capacity management
  capacity_limit integer,
  
  -- Branding and AI-generated content
  brand_color_primary text, -- Hex color code
  brand_color_secondary text, -- Hex color code
  ai_summary text, -- Generated by Gemini AI
  
  -- Metadata
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
comment on table events is 'Master event record. Central entity linking organizers, venues, tickets, schedules, and all event-related data.';
-- Enable row level security
alter table events enable row level security;
-- ============================================
-- EVENT SCHEDULES TABLE (Run of Show)
-- ============================================

-- Event schedules stores granular agenda items for the event day
-- Examples: "Doors Open", "Main Runway", "Networking Break"
create table event_schedules (
  id uuid default gen_random_uuid() primary key,
  event_id uuid references events(id) on delete cascade not null,
  
  -- Schedule item details
  title text not null, -- e.g. "Doors Open", "Main Runway", "Networking"
  description text,
  start_time timestamptz not null,
  end_time timestamptz,
  location_in_venue text, -- e.g. "Main Stage", "Backstage", "VIP Lounge"
  speaker_names text[], -- Array of speaker/participant names
  
  created_at timestamptz default now()
);
comment on table event_schedules is 'Granular agenda items for event day. Run of show timeline with specific activities and times.';
-- Enable row level security
alter table event_schedules enable row level security;
-- ============================================
-- RLS POLICIES FOR EVENTS
-- ============================================

-- Public (anon) can view published events only
create policy "anon can view published events"
  on events for select
  to anon
  using (status = 'published' and is_public = true);
-- Authenticated users can view published events
create policy "authenticated can view published events"
  on events for select
  to authenticated
  using (status = 'published' and is_public = true);
-- Organizers can view their own events (any status)
create policy "organizers can view own events"
  on events for select
  to authenticated
  using (auth.uid() = organizer_id);
-- Organizers can insert events
create policy "organizers can insert events"
  on events for insert
  to authenticated
  with check (auth.uid() = organizer_id);
-- Organizers can update their own events
create policy "organizers can update own events"
  on events for update
  to authenticated
  using (auth.uid() = organizer_id)
  with check (auth.uid() = organizer_id);
-- Organizers can delete their own events
create policy "organizers can delete own events"
  on events for delete
  to authenticated
  using (auth.uid() = organizer_id);
-- ============================================
-- RLS POLICIES FOR EVENT SCHEDULES
-- ============================================

-- Public can view schedules for published events
create policy "anon can view published event schedules"
  on event_schedules for select
  to anon
  using (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.status = 'published'
      and events.is_public = true
    )
  );
-- Authenticated can view schedules for published events
create policy "authenticated can view published event schedules"
  on event_schedules for select
  to authenticated
  using (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.status = 'published'
      and events.is_public = true
    )
  );
-- Organizers can view schedules for their events
create policy "organizers can view event schedules"
  on event_schedules for select
  to authenticated
  using (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.organizer_id = auth.uid()
    )
  );
-- Organizers can insert schedules for their events
create policy "organizers can insert event schedules"
  on event_schedules for insert
  to authenticated
  with check (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.organizer_id = auth.uid()
    )
  );
-- Organizers can update schedules for their events
create policy "organizers can update event schedules"
  on event_schedules for update
  to authenticated
  using (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.organizer_id = auth.uid()
    )
  )
  with check (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.organizer_id = auth.uid()
    )
  );
-- Organizers can delete schedules for their events
create policy "organizers can delete event schedules"
  on event_schedules for delete
  to authenticated
  using (
    exists (
      select 1 from events
      where events.id = event_schedules.event_id
      and events.organizer_id = auth.uid()
    )
  );
-- ============================================
-- INDEXES FOR EVENTS
-- ============================================

-- Index for organizer lookups (dashboard queries)
create index idx_events_organizer on events(organizer_id);
-- Index for status filtering (public event listings)
create index idx_events_status on events(status) where status = 'published';
-- Index for slug lookups (public event pages)
create index idx_events_slug on events(slug);
-- Index for date range queries (upcoming events)
-- Note: Cannot use now() in index predicate (not immutable), so we index all start_time values
create index idx_events_start_time on events(start_time);
-- Index for venue lookups
create index idx_events_venue on events(venue_id) where venue_id is not null;
-- ============================================
-- INDEXES FOR EVENT SCHEDULES
-- ============================================

-- Index for event schedule lookups
create index idx_event_schedules_event on event_schedules(event_id);
-- Index for time-based queries
create index idx_event_schedules_time on event_schedules(start_time);
